### ISSUE TITLE
how to install abyss2

### ISSUE THREAD

**Issue by Rohit-Satyam** [sjackman/giab#3]
Hi @sjackman 

I wish to use abyss2 for a resequencing project of humans. However, it is not clear from where to download and compile it. I have abyss already installed using `sudo apt-get install abyss`. I also tried cloning this repo and compile it. However, it throws following error:

>make -C abyss
make[1]: Entering directory '/home/baadalvm/rohit/abyss-2.0-giab/abyss'
cat: pe400.in: No such file or directory
make[1]: *** No rule to make target 'k144/GRCh38_hsapiens-scaftigs.samtobreak.tsv', needed by 'all'.  Stop.
make[1]: Leaving directory '/home/baadalvm/rohit/abyss-2.0-giab/abyss'
Makefile:309: recipe for target 'abyss/hsapiens-scaffolds.fa' failed
make: *** [abyss/hsapiens-scaffolds.fa] Error 2

I am new to this field so can you help where things are getting wrong. Are there some dependencies I am missing?

**Comment by sjackman** [comment]
The recommended way to install an up-to-date version of ABySS is with either Homebrew (preferred for both macOS and Linux) or BioConda. See https://brew.sh to install Homebrew, and then run `brew install abyss`.
